"""Add country entries

Revision ID: 65638549e2b6
Revises: ac41a312c0cd
Create Date: 2024-02-20 09:41:12.442164

"""

import csv
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65638549e2b6"
down_revision: Union[str, None] = "ac41a312c0cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with open("data/countries.csv", "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            op.execute(
                sa.text(
                    "INSERT INTO countries (code, code2, name, lat, lon) VALUES (:code3, :code2, :Name, :lat, :lon)"
                ).bindparams(
                    code3=row["code3"],
                    code2=row["code2"],
                    Name=row["Name"],
                    lat=float(row["Lat"]),
                    lon=float(row["Lon"]),
                )
            )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # do not delete countries as they maybe referenced in other tables
    # op.execute("DELETE FROM countries")
    # ### end Alembic commands ###
    pass
