"""add batch name to analyses

Revision ID: c695f567c4f1
Revises: 5ce093d2a6a5
Create Date: 2024-03-15 12:25:37.155135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c695f567c4f1"
down_revision: Union[str, None] = "5ce093d2a6a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analyses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("batch_name", sa.String(length=20), nullable=False)
        )

    with op.batch_alter_table("analyses_version", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "batch_name", sa.String(length=20), autoincrement=False, nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analyses_version", schema=None) as batch_op:
        batch_op.drop_column("batch_name")

    with op.batch_alter_table("analyses", schema=None) as batch_op:
        batch_op.drop_column("batch_name")

    # ### end Alembic commands ###
