"""nullable sub-species and analysis_date for speciation

Revision ID: f01fce5ded1d
Revises: c695f567c4f1
Create Date: 2024-03-19 12:02:46.689536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f01fce5ded1d"
down_revision: Union[str, None] = "c695f567c4f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("speciations", schema=None) as batch_op:
        batch_op.alter_column(
            "sub_species", existing_type=sa.VARCHAR(length=100), nullable=True
        )
        batch_op.alter_column("analysis_date", existing_type=sa.DATE(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("speciations", schema=None) as batch_op:
        batch_op.alter_column("analysis_date", existing_type=sa.DATE(), nullable=False)
        batch_op.alter_column(
            "sub_species", existing_type=sa.VARCHAR(length=100), nullable=False
        )

    # ### end Alembic commands ###
