name: Test
env:
  FORCE_COLOR: "1"
  PYTHONPATH: ${{ github.workspace }}/src
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run_tests:
    name: "tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Add PostgreSQL APT repository
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      - name: Update package list
        run: sudo apt-get update
      - name: Install PostgreSQL 16.4
        run: |
          sudo apt-get install -y postgresql-16
          sudo service postgresql start
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Lint
        run: |
          ruff check src/app
      - name: MyPy
        run: |
          mypy src/app
      - name: Tests
        run: |
          pytest src/app